--- Componente: CMP_MACHINE_CONDITIONS ---

--- Librerie ---
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;

--- Definizione della entità ---
ENTITY CMP_MACHINE_CONDITIONS IS
	PORT
	(
		INPUT_0  : IN  STD_LOGIC_VECTOR(7 DOWNTO 0);
		INPUT_1  : IN  STD_LOGIC_VECTOR(7 DOWNTO 0);
		INPUT_2  : IN  STD_LOGIC_VECTOR(7 DOWNTO 0);
		OUTPUT_0 : OUT STD_LOGIC;
		OUTPUT_1 : OUT STD_LOGIC
	);
END CMP_MACHINE_CONDITIONS;

--- Architettura (structural) del componente ---
ARCHITECTURE CMP_MACHINE_CONDITIONS_ARCH OF CMP_MACHINE_CONDITIONS IS
BEGIN
	OUTPUT_0 <= '1' WHEN INPUT_0 = "00000000" ELSE
		'0'; -- OUTPUT_0 è 1 sse INPUT_0 è 0
	OUTPUT_1 <= '1' WHEN (INPUT_1 /= "00000000" AND INPUT_2 /= "00000000") ELSE
		'0'; -- OUTPUT_1 è 1 sse INPUT_1 e INPUT_2 sono entrambi diversi da 0
END CMP_MACHINE_CONDITIONS_ARCH;