--- Componente: CMP_LOOP_CONDITION ---

--- Librerie ---
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

--- Definizione della entità ---
ENTITY CMP_LOOP_CONDITION IS
	PORT
	(
		INPUT_0 : IN  STD_LOGIC_VECTOR(9 DOWNTO 0);
		INPUT_1 : IN  STD_LOGIC_VECTOR(9 DOWNTO 0);
		OUTPUT  : OUT STD_LOGIC
	);
END CMP_LOOP_CONDITION;

--- Architettura (behavioural) del componente ---
ARCHITECTURE CMP_LOOP_CONDITION_ARCH OF CMP_LOOP_CONDITION IS
BEGIN
	PROCESS (INPUT_0, INPUT_1)
	BEGIN
		IF INPUT_0 = INPUT_1 THEN
			OUTPUT <= '1'; --- OUTPUT: Viene posto a 1 sse INPUT_0 = INPUT_1
		ELSE
			OUTPUT <= '0';
		END IF;
	END PROCESS;

END CMP_LOOP_CONDITION_ARCH;